//! Convert native path commands into the geometry contract's faithful paths
//! and its derived straight-line representation.

use pdfium::{PathObject, PathSegment, SegmentKind};
use std::sync::Arc;

use crate::model::{PaintStyle, Path, PathOp, Polyline, Segment};

const CURVE_FLATNESS_PTS: f64 = 0.25;
const MAX_CURVE_DEPTH: usize = 16;
const CLIP_LEFT: u8 = 1;
const CLIP_RIGHT: u8 = 2;
const CLIP_TOP: u8 = 4;
const CLIP_BOTTOM: u8 = 8;

#[derive(Default)]
pub struct PathCapture {
    pub paths: Vec<Path>,
    pub polylines: Vec<Polyline>,
    pub segments: Vec<Segment>,
    pub path_ops: usize,
}

impl PathCapture {
    pub fn paint(&mut self, object: &PathObject, style: &PaintStyle) -> Result<(), String> {
        if !object.is_filled && !object.is_stroked {
            return Ok(());
        }
        if !object.stroke_width.is_finite() {
            return Err("path has a nonfinite stroke width".into());
        }
        let mut fill = style.clone();
        fill.paint = "fill".into();
        fill.stroke_width = 0.0;
        let mut stroke = style.clone();
        stroke.paint = "stroke".into();
        stroke.stroke_width = f64::from(object.stroke_width);
        self.paint_commands(
            &object.segments,
            object.is_filled.then_some(&fill),
            object.is_stroked.then_some(&stroke),
        )
    }

    /// Record the two PDF paint callbacks independently: they can have different
    /// raw colorspaces, alpha and patterns even for the same source path.
    pub fn paint_commands(
        &mut self,
        commands: &[PathSegment],
        fill_style: Option<&PaintStyle>,
        stroke_style: Option<&PaintStyle>,
    ) -> Result<(), String> {
        self.paint_transformed_commands(commands, fill_style, stroke_style, |point| point)
    }

    /// Subdivide cubics in source space, evaluating flatness and emitted edges
    /// through the affine paint transform. This preserves source-coordinate rounding.
    pub fn paint_transformed_commands(
        &mut self,
        commands: &[PathSegment],
        fill_style: Option<&PaintStyle>,
        stroke_style: Option<&PaintStyle>,
        transform: impl Fn([f64; 2]) -> [f64; 2],
    ) -> Result<(), String> {
        if let Some(style) = fill_style {
            self.capture(commands, style.clone(), &transform)?;
        }
        if let Some(style) = stroke_style {
            self.capture(commands, style.clone(), &transform)?;
        }
        Ok(())
    }

    fn capture(
        &mut self,
        commands: &[PathSegment],
        style: PaintStyle,
        transform: &impl Fn([f64; 2]) -> [f64; 2],
    ) -> Result<(), String> {
        if style.clip_depth > 0 && style.clip_bbox.len() != 4 {
            return Err("active clip requires a four-coordinate bounding box".into());
        }
        if style.clip_depth > 0
            && (!style.clip_bbox.iter().all(|value| value.is_finite())
                || style.clip_bbox[0] > style.clip_bbox[2]
                || style.clip_bbox[1] > style.clip_bbox[3])
        {
            return Err("active clip has invalid bounds".into());
        }
        let style = Arc::new(style);
        self.path_ops += 1;
        let mut current: Option<[f64; 2]> = None;
        let mut start: Option<[f64; 2]> = None;
        let mut curve_controls = Vec::new();
        for command in commands {
            let point = [f64::from(command.x), f64::from(command.y)];
            let painted = transform(point);
            if !point
                .iter()
                .chain(painted.iter())
                .all(|coordinate| coordinate.is_finite())
            {
                return Err("path has a nonfinite coordinate".into());
            }
            match command.kind {
                SegmentKind::MoveTo => {
                    if !curve_controls.is_empty() {
                        return Err("incomplete cubic before moveto".into());
                    }
                    if start.is_some() {
                        self.finish_subpath(&style);
                    }
                    self.start_subpath(painted, &style);
                    start = Some(point);
                    current = Some(point);
                }
                SegmentKind::LineTo => {
                    if !curve_controls.is_empty() {
                        return Err("incomplete cubic before lineto".into());
                    }
                    // PDFium exposes the line generated by `h` with `close=true`.
                    // Keep that edge in Segments, but represent it as `close`
                    // alone in the source-fidelity path command stream.
                    if !(command.close && Some(point) == start) {
                        let previous = current.ok_or("lineto without moveto")?;
                        self.add_line(transform(previous), painted, &style);
                        self.path_op(PathOp {
                            kind: "lineto".into(),
                            x: painted[0],
                            y: painted[1],
                            ..empty_path_op()
                        });
                        current = Some(point);
                    }
                }
                SegmentKind::BezierTo => {
                    curve_controls.push(point);
                    if curve_controls.len() == 3 {
                        let previous = current.ok_or("curveto without moveto")?;
                        let controls = [curve_controls[0], curve_controls[1], curve_controls[2]];
                        let painted_controls = controls.map(transform);
                        self.path_op(PathOp {
                            kind: "curveto".into(),
                            x: painted_controls[2][0],
                            y: painted_controls[2][1],
                            ctrl1_x: painted_controls[0][0],
                            ctrl1_y: painted_controls[0][1],
                            ctrl2_x: painted_controls[1][0],
                            ctrl2_y: painted_controls[1][1],
                        });
                        self.flatten_curve(
                            [previous, controls[0], controls[1], controls[2]],
                            0,
                            &style,
                            transform,
                        );
                        current = Some(controls[2]);
                        curve_controls.clear();
                    }
                }
            }
            if command.close {
                if !curve_controls.is_empty() {
                    return Err("closepath inside cubic".into());
                }
                let first = start.ok_or("closepath without moveto")?;
                let previous = current.ok_or("closepath without current point")?;
                if previous != first {
                    self.add_line(transform(previous), transform(first), &style);
                }
                self.path_op(PathOp {
                    kind: "close".into(),
                    ..empty_path_op()
                });
                self.paths.last_mut().expect("started subpath").closed = true;
                self.polylines.last_mut().expect("started subpath").closed = true;
                current = Some(first);
            }
        }
        if !curve_controls.is_empty() {
            return Err("incomplete cubic at end of path".into());
        }
        if start.is_some() {
            self.finish_subpath(&style);
        }
        Ok(())
    }

    fn finish_subpath(&mut self, style: &PaintStyle) {
        if self.paths.len() == self.polylines.len()
            && self
                .segments
                .last()
                .is_none_or(|s| s.owner_path != self.paths.len())
            && self
                .paths
                .last()
                .is_some_and(|path| !path.closed || style.clip_depth > 0)
        {
            self.paths.pop();
            self.polylines.pop();
        }
    }

    fn start_subpath(&mut self, point: [f64; 2], style: &Arc<PaintStyle>) {
        self.paths.push(Path {
            ops: vec![PathOp {
                kind: "moveto".into(),
                x: point[0],
                y: point[1],
                ..empty_path_op()
            }],
            closed: false,
            style: style.clone(),
        });
        self.polylines.push(Polyline {
            points: vec![point],
            closed: false,
        });
    }

    fn path_op(&mut self, op: PathOp) {
        self.paths.last_mut().expect("started subpath").ops.push(op);
    }

    fn add_line(&mut self, from: [f64; 2], to: [f64; 2], style: &Arc<PaintStyle>) {
        let visible = if style.clip_depth > 0 {
            clip_line(from, to, &style.clip_bbox)
        } else {
            Some((from, to))
        };
        if let Some((start, end)) = visible {
            self.segments.push(Segment {
                x1: start[0],
                y1: start[1],
                x2: end[0],
                y2: end[1],
                owner_path: self.paths.len(),
                style: style.clone(),
            });
        }
        self.polylines
            .last_mut()
            .expect("started subpath")
            .points
            .push(to);
    }

    fn flatten_curve(
        &mut self,
        points: [[f64; 2]; 4],
        depth: usize,
        style: &Arc<PaintStyle>,
        transform: &impl Fn([f64; 2]) -> [f64; 2],
    ) {
        let painted = points.map(transform);
        let flatness = CURVE_FLATNESS_PTS * CURVE_FLATNESS_PTS;
        if depth >= MAX_CURVE_DEPTH
            || (point_line_distance_squared(painted[1], painted[0], painted[3]) <= flatness
                && point_line_distance_squared(painted[2], painted[0], painted[3]) <= flatness)
        {
            self.add_line(painted[0], painted[3], style);
            return;
        }
        let a = midpoint(points[0], points[1]);
        let b = midpoint(points[1], points[2]);
        let c = midpoint(points[2], points[3]);
        let d = midpoint(a, b);
        let e = midpoint(b, c);
        let f = midpoint(d, e);
        self.flatten_curve([points[0], a, d, f], depth + 1, style, transform);
        self.flatten_curve([f, e, c, points[3]], depth + 1, style, transform);
    }
}

fn clip_code(point: [f64; 2], rect: &[f64]) -> u8 {
    let mut code = 0;
    if point[0] < rect[0] {
        code |= CLIP_LEFT;
    } else if point[0] > rect[2] {
        code |= CLIP_RIGHT;
    }
    if point[1] < rect[1] {
        code |= CLIP_TOP;
    } else if point[1] > rect[3] {
        code |= CLIP_BOTTOM;
    }
    code
}

fn clip_line(mut start: [f64; 2], mut end: [f64; 2], rect: &[f64]) -> Option<([f64; 2], [f64; 2])> {
    let mut first = clip_code(start, rect);
    let mut last = clip_code(end, rect);
    loop {
        if first | last == 0 {
            return Some((start, end));
        }
        if first & last != 0 {
            return None;
        }
        let outside = if first != 0 { first } else { last };
        let point = if outside & CLIP_BOTTOM != 0 {
            if end[1] == start[1] {
                return None;
            }
            [
                start[0] + (end[0] - start[0]) * (rect[3] - start[1]) / (end[1] - start[1]),
                rect[3],
            ]
        } else if outside & CLIP_TOP != 0 {
            if end[1] == start[1] {
                return None;
            }
            [
                start[0] + (end[0] - start[0]) * (rect[1] - start[1]) / (end[1] - start[1]),
                rect[1],
            ]
        } else if outside & CLIP_RIGHT != 0 {
            if end[0] == start[0] {
                return None;
            }
            [
                rect[2],
                start[1] + (end[1] - start[1]) * (rect[2] - start[0]) / (end[0] - start[0]),
            ]
        } else {
            if end[0] == start[0] {
                return None;
            }
            [
                rect[0],
                start[1] + (end[1] - start[1]) * (rect[0] - start[0]) / (end[0] - start[0]),
            ]
        };
        if outside == first {
            start = point;
            first = clip_code(start, rect);
        } else {
            end = point;
            last = clip_code(end, rect);
        }
    }
}

fn midpoint(a: [f64; 2], b: [f64; 2]) -> [f64; 2] {
    [(a[0] + b[0]) * 0.5, (a[1] + b[1]) * 0.5]
}

fn point_line_distance_squared(point: [f64; 2], a: [f64; 2], b: [f64; 2]) -> f64 {
    let delta = [b[0] - a[0], b[1] - a[1]];
    let length_squared = delta[0] * delta[0] + delta[1] * delta[1];
    let fraction = if length_squared <= 0.0 {
        0.0
    } else {
        (((point[0] - a[0]) * delta[0] + (point[1] - a[1]) * delta[1]) / length_squared)
            .clamp(0.0, 1.0)
    };
    let projection = [a[0] + fraction * delta[0], a[1] + fraction * delta[1]];
    (point[0] - projection[0]).powi(2) + (point[1] - projection[1]).powi(2)
}

fn empty_path_op() -> PathOp {
    PathOp {
        kind: String::new(),
        x: 0.0,
        y: 0.0,
        ctrl1_x: 0.0,
        ctrl1_y: 0.0,
        ctrl2_x: 0.0,
        ctrl2_y: 0.0,
    }
}

#[cfg(test)]
mod tests {
    use pdfium::{PathObject, PathSegment, RectF, SegmentKind};

    use super::*;

    fn path(segments: Vec<PathSegment>, filled: bool, stroked: bool) -> PathObject {
        PathObject {
            bbox: RectF {
                left: 0.0,
                top: 10.0,
                right: 10.0,
                bottom: 0.0,
            },
            stroke_color: None,
            fill_color: None,
            stroke_width: 2.0,
            is_stroked: stroked,
            is_filled: filled,
            segments,
        }
    }

    fn command(kind: SegmentKind, x: f32, y: f32, close: bool) -> PathSegment {
        PathSegment { kind, x, y, close }
    }

    #[test]
    fn preserves_cubic_and_flattens_with_stable_owner() {
        let object = path(
            vec![
                command(SegmentKind::MoveTo, 0.0, 0.0, false),
                command(SegmentKind::BezierTo, 0.0, 10.0, false),
                command(SegmentKind::BezierTo, 10.0, 10.0, false),
                command(SegmentKind::BezierTo, 10.0, 0.0, false),
            ],
            false,
            true,
        );
        let mut capture = PathCapture::default();
        capture.paint(&object, &PaintStyle::default()).unwrap();
        assert_eq!(capture.path_ops, 1);
        assert_eq!(capture.paths.len(), 1);
        assert_eq!(capture.paths[0].ops.len(), 2);
        assert_eq!(capture.paths[0].ops[1].kind, "curveto");
        assert_eq!(capture.paths[0].ops[1].ctrl1_y, 10.0);
        assert_eq!(capture.paths[0].ops[1].ctrl2_x, 10.0);
        assert!(capture.segments.len() > 1);
        assert!(
            capture
                .segments
                .iter()
                .all(|segment| segment.owner_path == 1)
        );
        assert_eq!(
            capture.polylines[0].points.len(),
            capture.segments.len() + 1
        );
        assert_eq!(capture.segments.last().unwrap().x2, 10.0);
        assert!(
            capture
                .segments
                .iter()
                .all(|segment| { Arc::ptr_eq(&segment.style, &capture.paths[0].style) })
        );
        let encoded = serde_json::to_value(&capture.segments).unwrap();
        let decoded: Vec<Segment> = serde_json::from_value(encoded.clone()).unwrap();
        assert_eq!(serde_json::to_value(decoded).unwrap(), encoded);
        let mut changed = capture.segments[0].clone();
        Arc::make_mut(&mut changed.style).dash_array = vec![2.0];
        assert!(capture.paths[0].style.dash_array.is_empty());
        assert!(capture.segments[0].style.dash_array.is_empty());
        assert_eq!(changed.style.dash_array, [2.0]);
    }

    #[test]
    fn source_cubic_subdivision_rounds_each_endpoint_through_the_paint_transform() {
        const MIDPOINT_WEIGHTS: [f64; 4] = [0.125, 0.375, 0.375, 0.125];
        const SCALE: [f32; 2] = [3.25, 0.75];
        const OFFSET: [f32; 2] = [1000.123, 2000.321];
        let source = [[0.13f32, 0.2], [0.2, 30.1], [0.27, 30.2], [0.34, 0.4]];
        let commands = source
            .iter()
            .enumerate()
            .map(|(index, point)| {
                command(
                    if index == 0 {
                        SegmentKind::MoveTo
                    } else {
                        SegmentKind::BezierTo
                    },
                    point[0],
                    point[1],
                    false,
                )
            })
            .collect::<Vec<_>>();
        let transform = |point: [f64; 2]| {
            [
                f64::from(point[0] as f32 * SCALE[0] + OFFSET[0]),
                f64::from(point[1] as f32 * SCALE[1] + OFFSET[1]),
            ]
        };
        let midpoint = transform(std::array::from_fn(|axis| {
            source
                .iter()
                .zip(MIDPOINT_WEIGHTS)
                .map(|(point, weight)| f64::from(point[axis]) * weight)
                .sum()
        }));
        let mut capture = PathCapture::default();
        capture
            .paint_transformed_commands(&commands, None, Some(&PaintStyle::default()), transform)
            .unwrap();
        assert!(capture.segments.len() > 1);
        assert!(
            capture
                .segments
                .iter()
                .any(|segment| [segment.x2, segment.y2] == midpoint)
        );
        for segment in &capture.segments {
            for value in [segment.x1, segment.y1, segment.x2, segment.y2] {
                assert_eq!(value, f64::from(value as f32));
            }
        }
        assert_eq!(capture.paths[0].ops[1].kind, "curveto");
        assert_eq!(
            [
                capture.paths[0].ops[1].ctrl1_x,
                capture.paths[0].ops[1].ctrl1_y
            ],
            transform(source[1].map(f64::from))
        );
    }

    #[test]
    fn dual_paint_closes_each_subpath_without_fabricating_raw_line() {
        let object = path(
            vec![
                command(SegmentKind::MoveTo, 0.0, 0.0, false),
                command(SegmentKind::LineTo, 10.0, 0.0, false),
                command(SegmentKind::LineTo, 10.0, 10.0, true),
            ],
            true,
            true,
        );
        let mut capture = PathCapture::default();
        capture.paint(&object, &PaintStyle::default()).unwrap();
        assert_eq!(capture.path_ops, 2);
        assert_eq!(capture.paths.len(), 2);
        assert_eq!(capture.segments.len(), 6);
        assert_eq!(capture.paths[0].style.paint, "fill");
        assert_eq!(capture.paths[1].style.paint, "stroke");
        assert_eq!(capture.paths[1].style.stroke_width, 2.0);
        assert_eq!(
            capture.paths[0]
                .ops
                .iter()
                .map(|op| op.kind.as_str())
                .collect::<Vec<_>>(),
            ["moveto", "lineto", "lineto", "close"]
        );
        assert!(capture.paths.iter().all(|path| path.closed));
        assert_eq!(capture.segments[0].owner_path, 1);
        assert_eq!(capture.segments[3].owner_path, 2);
    }

    #[test]
    fn clipped_subpath_keeps_visible_owner_numbering() {
        let object = path(
            vec![
                command(SegmentKind::MoveTo, 120.0, 10.0, false),
                command(SegmentKind::LineTo, 190.0, 10.0, false),
                command(SegmentKind::MoveTo, 10.0, 10.0, false),
                command(SegmentKind::LineTo, 90.0, 10.0, false),
            ],
            false,
            true,
        );
        let style = PaintStyle {
            clip_depth: 1,
            clip_bbox: vec![0.0, 0.0, 80.0, 200.0],
            ..PaintStyle::default()
        };
        let mut capture = PathCapture::default();
        capture.paint(&object, &style).unwrap();
        assert_eq!(capture.path_ops, 1);
        assert_eq!(capture.paths.len(), 1);
        assert_eq!(capture.segments.len(), 1);
        assert_eq!(capture.segments[0].owner_path, 1);
        assert_eq!(capture.segments[0].x1, 10.0);
        assert_eq!(capture.segments[0].x2, 80.0);
        assert_eq!(capture.polylines[0].points[1][0], 90.0);
    }
}
